### ISSUE TITLE
name of uavcan library

### ISSUE THREAD

**Issue by PonomarevDA** [PrincePepper/inno_uavcan_VTOL_interface#1]
It seems to be the library was renamed from `uavcan` to `pyuavcan_v0` few days ago.
Check here: https://github.com/UAVCAN/pyuavcan/issues/166
Maybe you need to merge these fixes: https://github.com/UAVCAN/gui_tool/commit/a4316a912eb1286f39a8f2dceecda2fd6d424f45 or do something similar.

**Comment by PrincePepper** [comment]
Thanks! At the moment, I think this is not critical, since we are not planning to deploy it except for our devices yet. We will definitely fix it in the future. I leave the question open for now.
